mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink-1.18 -Dversion=1.0-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-1.18/target/paimon-flink-1.18-1.0-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-1.18/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink-common -Dversion=1.0-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-common/target/paimon-flink-common-1.0-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-common/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-bundle -Dversion=1.0-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-bundle/target/paimon-bundle-1.0-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-bundle/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-service-runtime -Dversion=1.0-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-runtime/target/paimon-service-runtime-1.0-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-runtime/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-service-client -Dversion=1.0-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-client/target/paimon-service-client-1.0-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-client/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-service -Dversion=1.0-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink -Dversion=1.0-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-parent -Dversion=1.0-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/pom.xml
