mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-common -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-common/target/paimon-common-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-common/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-core -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-core/target/paimon-core-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-core/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-format -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-format/target/paimon-format-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-format/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-hive-common -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-hive/paimon-hive-common/target/paimon-hive-common-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-hive/paimon-hive-common/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-hive-catalog -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-hive/paimon-hive-catalog/target/paimon-hive-catalog-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-hive/paimon-hive-catalog/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink-1.18 -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-1.18/target/paimon-flink-1.18-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-1.18/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink-cdc -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-cdc/target/paimon-flink-cdc-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-cdc/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink-common -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-common/target/paimon-flink-common-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/paimon-flink-common/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-bundle -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-bundle/target/paimon-bundle-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-bundle/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-codegen-loader -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-codegen-loader/target/paimon-codegen-loader-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-codegen-loader/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-service-runtime -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-runtime/target/paimon-service-runtime-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-runtime/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-service-client -Dversion=1.1-SNAPSHOT -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-client/target/paimon-service-client-1.1-SNAPSHOT.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/paimon-service-client/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-service -Dversion=1.1-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-service/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-flink -Dversion=1.1-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-flink/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-hive -Dversion=1.1-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-hive/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/paimon-hive/pom.xml

mvn org.apache.maven.plugins:maven-install-plugin:2.5::install-file -DgroupId=org.apache.paimon -DartifactId=paimon-parent -Dversion=1.1-SNAPSHOT  -Dfile=/Users/xingcan/IdeaProjects/incubator-paimon/pom.xml -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -DpomFile=/Users/xingcan/IdeaProjects/incubator-paimon/pom.xml
